---
parameters:
  compiler: "cc"
  options: ""
  wrapper: ""
  prepare: ""

steps:
  - script: |
      ${{ parameters.prepare }}
      meson setup ${{ parameters.options }} build
    displayName: 'Setup'
    env:
      CC: ${{ parameters.compiler }}

  - script: |
      ${{ parameters.prepare }}
      ninja -C build
    displayName: 'Build'
    env:
      TERM: dumb

  - bash: |
      set -euo pipefail
      meson test -C build --print-errorlogs --wrapper="${{ parameters.wrapper }}"
      python3 scripts/meson-junit-report.py --project-name=xkbcommon \
        --job-id='$(Build.BuildId)' --branch='$(Build.SourceBranch)' \
        --output=testlog.xml build/meson-logs/testlog*.json
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'testlog.xml'
      failTaskOnFailedTests: true
