---
jobs:
  - job: 'Meson'
    dependsOn: []
    strategy:
      matrix:
        Clang:
          compiler: clang
        GCC:
          compiler: gcc
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/steps/dependencies-linux.yml
      - template: .azure-pipelines/steps/meson.yml
        parameters:
          compiler: $(compiler)
          options: -Denable-wayland=false
          wrapper: valgrind --leak-check=full --track-origins=yes --error-exitcode=99
  - job: 'Autotools'
    dependsOn: []
    strategy:
      matrix:
        Clang:
          compiler: clang
        GCC:
          compiler: gcc
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/steps/dependencies-linux.yml
      - template: .azure-pipelines/steps/autotools.yml
        parameters:
          compiler: $(compiler)
  - job: 'macOS'
    dependsOn: []
    pool:
      vmImage: 'macos-10.13'
    steps:
      - template: .azure-pipelines/steps/dependencies-macos.yml
      - template: .azure-pipelines/steps/meson.yml
        parameters:
          options: -Denable-wayland=false -Denable-x11=false
